version: "3.8"

services:
  circom:
    container_name: circom
    image: circom:unoptimized
    build: ./images/circom/
    working_dir: /sindri-project/
    volumes:
      - ./images/circom/:/sindri-project/

  circomspect:
    container_name: circomspect
    image: circomspect:unoptimized
    build: ./images/circomspect/
    working_dir: /sindri-project/
    volumes:
      - ./images/circomspect/:/sindri-project/
