version: "3.8"

services:
  circom:
    container_name: circom
    image: circom:unoptimized
    build: ./images/circom/
    working_dir: /sindri/
    volumes:
      - ./images/circom/:/sindri/

  circomspect:
    container_name: circomspect
    image: circomspect:unoptimized
    build: ./images/circomspect/
    working_dir: /sindri/
    volumes:
      - ./images/circomspect/:/sindri/

  nargo:
    container_name: nargo
    image: nargo:unoptimized
    build: ./images/nargo/
    platform: linux/amd64
    working_dir: /sindri/
    volumes:
      - ./images/nargo/:/sindri/

  snarkjs:
    container_name: snarkjs
    image: snarkjs:unoptimized
    build: ./images/snarkjs/
    working_dir: /sindri/
    volumes:
      - ./images/snarkjs/:/sindri/
