name: Build Images

on:
  push:
    branches: ["main"]
    tags:
      - "v*"
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        image: ["circom", "circomspect", "nargo", "snarkjs"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Image
        run: |
          docker buildx build -f images/${{ matrix.image }}/Dockerfile -t ${{ matrix.image }}:unoptimized --load images/${{ matrix.image }}/

      - name: Install SlimTookit
        run: |
          curl -sL https://raw.githubusercontent.com/slimtoolkit/slim/master/scripts/install-slim.sh | sudo -E bash -

      - name: Build Optimized Image
        run: |
          slim build --target ${{ matrix.image }}:unoptimized \
            --tag sindrilabs/${{ matrix.image }}:dev \
            --http-probe=false \
            --exclude-pattern '/tmp/*' \
            --mount "./images/${{ matrix.image }}/:/sindri/" \
            --exec "./test.sh"

      - name: Deploy to DockerHub
        run: |
          docker push sindrilabs/${{ matrix.image }}:dev
